[username]
disabled = false
show_always = true

[shell]
unknown_indicator = 'mystery shell'
style = 'cyan bold'
disabled = false

#[battery]
#full_symbol = 'ğŸ”‹ '
#charging_symbol = 'âš¡ï¸'
#discharging_symbol = 'ğŸ’¦ '
#disabled = false

#[[battery.display]]
#threshold = 100
#style = 'bold green'

#[os]
#format = "[$symbol]($style) "
#style = "bold blue"
#disabled = false

#[os.symbols]
#Ubuntu = "ğŸ¯"
#Arch = "ğŸ—ï¸"
#Debian = "ğŸŒ€"
#Windows = "ğŸªŸ"

#[memory_usage]
#format = '$symbol[${ram_pct}]($style)'
#disabled = false
#threshold = -1
#symbol = 'ğŸ '
#style = 'bold dimmed green'

#[time]
#disabled = false
#format = 'at ğŸ•™ [$time]($style) '
#time_format = '%T'
#utc_time_offset = '+8'
